<a href="https://colab.research.google.com/github/Nav0k/IS170--digital-binder/blob/main/Kloy_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Gapminder Dataset: https://github.com/chendaniely/pandas_for_everyone/blob/master/data/gapminder.tsv

In [12]:
# Navpreet Kloy, Milan

import pandas as pd
import numpy as np

pd.read_csv('gapminder.tsv', delimiter='\t')  # reads the gapminder file
df = pd.read_csv('gapminder.tsv', delimiter='\t') # gapminder file read and stored in df

print(df.isnull().sum())  # Counts the number of missing (NaN) values in each column

country      0
continent    0
year         0
lifeExp      0
pop          0
gdpPercap    0
dtype: int64

In [13]:
# Standardize selected columns
from sklearn import preprocessing #import tool to standardize scale

scale = ['lifeExp', 'pop', 'gdpPercap'] # columns to be scaled from gapminder stored into variable

df[scale] = preprocessing.scale(df[scale])  # selected columns scaled and replaced in df DataFrame

df #displays updated DataFrame

          country continent  year   lifeExp       pop  gdpPercap
0     Afghanistan      Asia  1952 -2.375334 -0.199534  -0.653087
1     Afghanistan      Asia  1957 -2.256774 -0.191849  -0.648885
2     Afghanistan      Asia  1962 -2.127837 -0.182180  -0.645612
3     Afghanistan      Asia  1967 -1.971178 -0.170204  -0.647328
4     Afghanistan      Asia  1972 -1.811033 -0.155679  -0.657091
...           ...       ...   ...       ...       ...        ...
1699     Zimbabwe    Africa  1987  0.222759 -0.192080  -0.660524
1700     Zimbabwe    Africa  1992  0.069894 -0.178059  -0.661816
1701     Zimbabwe    Africa  1997 -0.980805 -0.171458  -0.651767
1702     Zimbabwe    Africa  2002 -1.508942 -0.166543  -0.663986
1703     Zimbabwe    Africa  2007 -1.238058 -0.162919  -0.684517

[1704 rows x 6 columns]

In [14]:
# Reording column headers
old_cols=df.columns.values # coverts and stores the column index to a NumPy array
new_cols=['year','country','continent',	'pop','lifeExp','gdpPercap'] # creates new list with desired reorder
df= df.reindex(columns=new_cols) # reorders the DataFrame columns as specified in new_cols
df #displays the DataFrame

      year      country continent       pop   lifeExp  gdpPercap
0     1952  Afghanistan      Asia -0.199534 -2.375334  -0.653087
1     1957  Afghanistan      Asia -0.191849 -2.256774  -0.648885
2     1962  Afghanistan      Asia -0.182180 -2.127837  -0.645612
3     1967  Afghanistan      Asia -0.170204 -1.971178  -0.647328
4     1972  Afghanistan      Asia -0.155679 -1.811033  -0.657091
...    ...          ...       ...       ...       ...        ...
1699  1987     Zimbabwe    Africa -0.192080  0.222759  -0.660524
1700  1992     Zimbabwe    Africa -0.178059  0.069894  -0.661816
1701  1997     Zimbabwe    Africa -0.171458 -0.980805  -0.651767
1702  2002     Zimbabwe    Africa -0.166543 -1.508942  -0.663986
1703  2007     Zimbabwe    Africa -0.162919 -1.238058  -0.684517

[1704 rows x 6 columns]

In [15]:
# Renaming column headers
print(df.rename(columns={'pop':'population'}))  # prints DataFrame with renamed column

      year      country continent  population   lifeExp  gdpPercap
0     1952  Afghanistan      Asia   -0.199534 -2.375334  -0.653087
1     1957  Afghanistan      Asia   -0.191849 -2.256774  -0.648885
2     1962  Afghanistan      Asia   -0.182180 -2.127837  -0.645612
3     1967  Afghanistan      Asia   -0.170204 -1.971178  -0.647328
4     1972  Afghanistan      Asia   -0.155679 -1.811033  -0.657091
...    ...          ...       ...         ...       ...        ...
1699  1987     Zimbabwe    Africa   -0.192080  0.222759  -0.660524
1700  1992     Zimbabwe    Africa   -0.178059  0.069894  -0.661816
1701  1997     Zimbabwe    Africa   -0.171458 -0.980805  -0.651767
1702  2002     Zimbabwe    Africa   -0.166543 -1.508942  -0.663986
1703  2007     Zimbabwe    Africa   -0.162919 -1.238058  -0.684517

[1704 rows x 6 columns]

In [16]:
# Converting String to Numeric Values
from sklearn.preprocessing import LabelEncoder #LabelEncoder imported from sklearn.preprocessing

le = LabelEncoder()  # Instance of LabelEncoder created

label = le.fit_transform(df['continent']) #LabelEncoder finds unique continent values and transforms them into integers, which are saved into label

df.drop("continent",axis=1, inplace=True)  # removes the original 'continent' column
df["continent"] = label # appends the encoded label with columns name 'continent
df #displays DataFrame, in this showcasing the updated encoded continent column

      year      country       pop   lifeExp  gdpPercap  continent
0     1952  Afghanistan -0.199534 -2.375334  -0.653087          2
1     1957  Afghanistan -0.191849 -2.256774  -0.648885          2
2     1962  Afghanistan -0.182180 -2.127837  -0.645612          2
3     1967  Afghanistan -0.170204 -1.971178  -0.647328          2
4     1972  Afghanistan -0.155679 -1.811033  -0.657091          2
...    ...          ...       ...       ...        ...        ...
1699  1987     Zimbabwe -0.192080  0.222759  -0.660524          0
1700  1992     Zimbabwe -0.178059  0.069894  -0.661816          0
1701  1997     Zimbabwe -0.171458 -0.980805  -0.651767          0
1702  2002     Zimbabwe -0.166543 -1.508942  -0.663986          0
1703  2007     Zimbabwe -0.162919 -1.238058  -0.684517          0

[1704 rows x 6 columns]

###Tesla Stock Dataset: https://github.com/chendaniely/pandas_for_everyone/blob/master/data/tesla_stock_yahoo.csv

In [17]:

tesla_stock_yahoo_df = pd.read_csv('tesla_stock_yahoo.csv', delimiter=',')  # tesla stock file read and stored in tesla_stock_yahoo_df

print(tesla_stock_yahoo_df.isnull().sum())  # Counts the number of missing (NaN) values in each column

tesla_stock_yahoo_df.head() #prints first five rows of DataFrame

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

         Date       Open   High        Low      Close  Adj Close    Volume
0  2010-06-29  19.000000  25.00  17.540001  23.889999  23.889999  18766300
1  2010-06-30  25.790001  30.42  23.299999  23.830000  23.830000  17187100
2  2010-07-01  25.000000  25.92  20.270000  21.959999  21.959999   8218800
3  2010-07-02  23.000000  23.10  18.709999  19.200001  19.200001   5139800
4  2010-07-06  20.000000  20.00  15.830000  16.110001  16.110001   6866900

In [18]:
# Standardize selected columns
from sklearn import preprocessing #import tool to standardize scale

scale = ['Open', 'High', 'Low','Close','Adj Close','Volume'] # columns to be scaled from gapminder stored into variable


tesla_stock_yahoo_df[scale] = preprocessing.scale(tesla_stock_yahoo_df[scale])  # selected columns scaled and replaced in df DataFrame

tesla_stock_yahoo_df #displays updated DataFrame

            Date      Open      High       Low     Close  Adj Close    Volume
0     2010-06-29 -1.217754 -1.166665 -1.225514 -1.169765  -1.169765  3.324371
1     2010-06-30 -1.151101 -1.114187 -1.168082 -1.170354  -1.170354  2.957710
2     2010-07-01 -1.158856 -1.157757 -1.198293 -1.188713  -1.188713  0.875440
3     2010-07-02 -1.178488 -1.185061 -1.213848 -1.215810  -1.215810  0.160554
4     2010-07-06 -1.207938 -1.215075 -1.242564 -1.246146  -1.246146  0.561554
...          ...       ...       ...       ...       ...        ...       ...
1786  2017-08-02  1.726572  1.758510  1.702731  1.795158   1.795158  2.006789
1787  2017-08-03  1.985626  1.980038  2.021101  2.003292   2.003292  2.109762
1788  2017-08-04  2.002020  2.050427  2.022597  2.099701   2.099701  1.102885
1789  2017-08-07  2.103619  2.071825  2.116822  2.082619   2.082619  0.424567
1790  2017-08-08  2.105386  2.159932  2.163186  2.181286   2.181286  0.696901

[1791 rows x 7 columns]

In [19]:
# Reording column headers
old_cols=tesla_stock_yahoo_df.columns.values # coverts and stores the column index to a NumPy array
new_cols=['Date','Low', 'High', 'Open','Close','Adj Close','Volume'] # creates new list with desired reorder
tesla_stock_yahoo_df= tesla_stock_yahoo_df.reindex(columns=new_cols) # reorders the DataFrame columns as specified in new_cols
tesla_stock_yahoo_df #displays the DataFrame

            Date       Low      High      Open     Close  Adj Close    Volume
0     2010-06-29 -1.225514 -1.166665 -1.217754 -1.169765  -1.169765  3.324371
1     2010-06-30 -1.168082 -1.114187 -1.151101 -1.170354  -1.170354  2.957710
2     2010-07-01 -1.198293 -1.157757 -1.158856 -1.188713  -1.188713  0.875440
3     2010-07-02 -1.213848 -1.185061 -1.178488 -1.215810  -1.215810  0.160554
4     2010-07-06 -1.242564 -1.215075 -1.207938 -1.246146  -1.246146  0.561554
...          ...       ...       ...       ...       ...        ...       ...
1786  2017-08-02  1.702731  1.758510  1.726572  1.795158   1.795158  2.006789
1787  2017-08-03  2.021101  1.980038  1.985626  2.003292   2.003292  2.109762
1788  2017-08-04  2.022597  2.050427  2.002020  2.099701   2.099701  1.102885
1789  2017-08-07  2.116822  2.071825  2.103619  2.082619   2.082619  0.424567
1790  2017-08-08  2.163186  2.159932  2.105386  2.181286   2.181286  0.696901

[1791 rows x 7 columns]

In [20]:
# Renaming column headers
print(tesla_stock_yahoo_df.rename(columns={'Adj Close':'Adjusted Closing', 'Volume':'Vol'}))  # prints DataFrame with renamed column

            Date       Low      High      Open     Close  Adjusted Closing  \
0     2010-06-29 -1.225514 -1.166665 -1.217754 -1.169765         -1.169765
1     2010-06-30 -1.168082 -1.114187 -1.151101 -1.170354         -1.170354
2     2010-07-01 -1.198293 -1.157757 -1.158856 -1.188713         -1.188713
3     2010-07-02 -1.213848 -1.185061 -1.178488 -1.215810         -1.215810
4     2010-07-06 -1.242564 -1.215075 -1.207938 -1.246146         -1.246146
...          ...       ...       ...       ...       ...               ...
1786  2017-08-02  1.702731  1.758510  1.726572  1.795158          1.795158
1787  2017-08-03  2.021101  1.980038  1.985626  2.003292          2.003292
1788  2017-08-04  2.022597  2.050427  2.002020  2.099701          2.099701
1789  2017-08-07  2.116822  2.071825  2.103619  2.082619          2.082619
1790  2017-08-08  2.163186  2.159932  2.105386  2.181286          2.181286

           Vol
0     3.324371
1     2.957710
2     0.875440
3     0.160554
4     0.561554
...        ...
1786  2.006789
1787  2.109762
1788  1.102885
1789  0.424567
1790  0.696901

[1791 rows x 7 columns]

In [21]:
# Converting String to Numeric Values
from sklearn.preprocessing import LabelEncoder #LabelEncoder imported from sklearn.preprocessing

le = LabelEncoder()  # Instance of LabelEncoder created

label = le.fit_transform(tesla_stock_yahoo_df['Date']) #LabelEncoder finds unique Date values and transforms them into integers, which are saved into label

tesla_stock_yahoo_df.drop("Date",axis=1, inplace=True)  # removes the original 'Date' column
tesla_stock_yahoo_df["Date"] = label # appends the encoded label to Date column
tesla_stock_yahoo_df #displays DataFrame with Date column encoded

           Low      High      Open     Close  Adj Close    Volume  Date
0    -1.225514 -1.166665 -1.217754 -1.169765  -1.169765  3.324371     0
1    -1.168082 -1.114187 -1.151101 -1.170354  -1.170354  2.957710     1
2    -1.198293 -1.157757 -1.158856 -1.188713  -1.188713  0.875440     2
3    -1.213848 -1.185061 -1.178488 -1.215810  -1.215810  0.160554     3
4    -1.242564 -1.215075 -1.207938 -1.246146  -1.246146  0.561554     4
...        ...       ...       ...       ...        ...       ...   ...
1786  1.702731  1.758510  1.726572  1.795158   1.795158  2.006789  1786
1787  2.021101  1.980038  1.985626  2.003292   2.003292  2.109762  1787
1788  2.022597  2.050427  2.002020  2.099701   2.099701  1.102885  1788
1789  2.116822  2.071825  2.103619  2.082619   2.082619  0.424567  1789
1790  2.163186  2.159932  2.105386  2.181286   2.181286  0.696901  1790

[1791 rows x 7 columns]

###Online Retail Dataset: https://archive.ics.uci.edu/dataset/352/online+retail

In [22]:

Online_Retail_df = pd.read_excel('Online Retail.xlsx')   # online retail file read and stored

print(Online_Retail_df.isnull().sum())  # Counts the number of missing (NaN) values in each column

Online_Retail_df.head() # prints first five rows of DataFrame

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [23]:
# Standardize selected columns
from sklearn import preprocessing #import tool to standardize scale

scale = ['Quantity', 'UnitPrice'] # columns to be scaled from gapminder stored into variable


Online_Retail_df[scale] = preprocessing.scale(Online_Retail_df[scale])  # selected columns scaled and replaced in df DataFrame

Online_Retail_df #displays updated DataFrame

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,-0.016289,2010-12-01 08:26:00,-0.021301,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,-0.016289,2010-12-01 08:26:00,-0.012620,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,-0.007118,2010-12-01 08:26:00,-0.019234,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,-0.016289,2010-12-01 08:26:00,-0.012620,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,-0.016289,2010-12-01 08:26:00,-0.012620,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,0.011224,2011-12-09 12:50:00,-0.038871,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,-0.016289,2011-12-09 12:50:00,-0.025952,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,-0.025460,2011-12-09 12:50:00,-0.004766,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,-0.025460,2011-12-09 12:50:00,-0.004766,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,-0.030045,2011-12-09 12:50:00,0.003502,12680.0,France

In [24]:
# Reording column headers
old_cols=Online_Retail_df.columns.values # coverts and stores the column index to a NumPy array
new_cols=['CustomerID','InvoiceNo','Country',	'InvoiceDate','Description','Quantity','UnitPrice', 'StockCode'] # creates new list with desired reorder
Online_Retail_df= Online_Retail_df.reindex(columns=new_cols) # reorders the DataFrame columns as specified in new_cols
Online_Retail_df #displays the DataFrame

,CustomerID,InvoiceNo,Country,InvoiceDate,Description,Quantity,UnitPrice,StockCode
0,17850.0,536365,United Kingdom,2010-12-01 08:26:00,WHITE HANGING HEART T-LIGHT HOLDER,-0.016289,-0.021301,85123A
1,17850.0,536365,United Kingdom,2010-12-01 08:26:00,WHITE METAL LANTERN,-0.016289,-0.012620,71053
2,17850.0,536365,United Kingdom,2010-12-01 08:26:00,CREAM CUPID HEARTS COAT HANGER,-0.007118,-0.019234,84406B
3,17850.0,536365,United Kingdom,2010-12-01 08:26:00,KNITTED UNION FLAG HOT WATER BOTTLE,-0.016289,-0.012620,84029G
4,17850.0,536365,United Kingdom,2010-12-01 08:26:00,RED WOOLLY HOTTIE WHITE HEART.,-0.016289,-0.012620,84029E
...,...,...,...,...,...,...,...,...
541904,12680.0,581587,France,2011-12-09 12:50:00,PACK OF 20 SPACEBOY NAPKINS,0.011224,-0.038871,22613
541905,12680.0,581587,France,2011-12-09 12:50:00,CHILDREN'S APRON DOLLY GIRL,-0.016289,-0.025952,22899
541906,12680.0,581587,France,2011-12-09 12:50:00,CHILDRENS CUTLERY DOLLY GIRL,-0.025460,-0.004766,23254
541907,12680.0,581587,France,2011-12-09 12:50:00,CHILDRENS CUTLERY CIRCUS PARADE,-0.025460,-0.004766,23255
541908,12680.0,581587,France,2011-12-09 12:50:00,BAKING SET 9 PIECE RETROSPOT,-0.030045,0.003502,22138

In [25]:
# Renaming column headers
print(Online_Retail_df.rename(columns={'CustomerID':'CustID', 'InvoiceNo':'InvNo'}))  # prints DataFrame with renamed column

         CustID   InvNo         Country         InvoiceDate  \
0       17850.0  536365  United Kingdom 2010-12-01 08:26:00
1       17850.0  536365  United Kingdom 2010-12-01 08:26:00
2       17850.0  536365  United Kingdom 2010-12-01 08:26:00
3       17850.0  536365  United Kingdom 2010-12-01 08:26:00
4       17850.0  536365  United Kingdom 2010-12-01 08:26:00
...         ...     ...             ...                 ...
541904  12680.0  581587          France 2011-12-09 12:50:00
541905  12680.0  581587          France 2011-12-09 12:50:00
541906  12680.0  581587          France 2011-12-09 12:50:00
541907  12680.0  581587          France 2011-12-09 12:50:00
541908  12680.0  581587          France 2011-12-09 12:50:00

                                Description  Quantity  UnitPrice StockCode
0        WHITE HANGING HEART T-LIGHT HOLDER -0.016289  -0.021301    85123A
1                       WHITE METAL LANTERN -0.016289  -0.012620     71053
2            CREAM CUPID HEARTS COAT HANGER -0.007118  -0.019234    84406B
3       KNITTED UNION FLAG HOT WATER BOTTLE -0.016289  -0.012620    84029G
4            RED WOOLLY HOTTIE WHITE HEART. -0.016289  -0.012620    84029E
...                                     ...       ...        ...       ...
541904          PACK OF 20 SPACEBOY NAPKINS  0.011224  -0.038871     22613
541905         CHILDREN'S APRON DOLLY GIRL  -0.016289  -0.025952     22899
541906        CHILDRENS CUTLERY DOLLY GIRL  -0.025460  -0.004766     23254
541907      CHILDRENS CUTLERY CIRCUS PARADE -0.025460  -0.004766     23255
541908        BAKING SET 9 PIECE RETROSPOT  -0.030045   0.003502     22138

[541909 rows x 8 columns]

In [26]:
# Converting String to Numeric Values
from sklearn.preprocessing import LabelEncoder #LabelEncoder imported from sklearn.preprocessing

le = LabelEncoder()  # Instance of LabelEncoder created

label = le.fit_transform(Online_Retail_df['Country']) #LabelEncoder finds unique Date values and transforms them into integers

Online_Retail_df.drop("Country",axis=1, inplace=True)  # removes the original 'Country' column
Online_Retail_df["Country"] = label # appends the encoded label to Date column
Online_Retail_df #displays DataFrame with Date column encoded

,CustomerID,InvoiceNo,InvoiceDate,Description,Quantity,UnitPrice,StockCode,Country
0,17850.0,536365,2010-12-01 08:26:00,WHITE HANGING HEART T-LIGHT HOLDER,-0.016289,-0.021301,85123A,36
1,17850.0,536365,2010-12-01 08:26:00,WHITE METAL LANTERN,-0.016289,-0.012620,71053,36
2,17850.0,536365,2010-12-01 08:26:00,CREAM CUPID HEARTS COAT HANGER,-0.007118,-0.019234,84406B,36
3,17850.0,536365,2010-12-01 08:26:00,KNITTED UNION FLAG HOT WATER BOTTLE,-0.016289,-0.012620,84029G,36
4,17850.0,536365,2010-12-01 08:26:00,RED WOOLLY HOTTIE WHITE HEART.,-0.016289,-0.012620,84029E,36
...,...,...,...,...,...,...,...,...
541904,12680.0,581587,2011-12-09 12:50:00,PACK OF 20 SPACEBOY NAPKINS,0.011224,-0.038871,22613,13
541905,12680.0,581587,2011-12-09 12:50:00,CHILDREN'S APRON DOLLY GIRL,-0.016289,-0.025952,22899,13
541906,12680.0,581587,2011-12-09 12:50:00,CHILDRENS CUTLERY DOLLY GIRL,-0.025460,-0.004766,23254,13
541907,12680.0,581587,2011-12-09 12:50:00,CHILDRENS CUTLERY CIRCUS PARADE,-0.025460,-0.004766,23255,13
541908,12680.0,581587,2011-12-09 12:50:00,BAKING SET 9 PIECE RETROSPOT,-0.030045,0.003502,22138,13